### ISSUE TITLE
take without drop is very surprising

### ISSUE THREAD

**Issue by michaelficarra** [tc39-transfer/proposal-iterator-helpers#11]
We don't have to have `take`, but if we do, it should coincide with `drop`. As a user, I would be very surprised to be able to use one and not the other.

**Comment by rbuckton** [comment]
I agree, though my preference is on `skip` vs `drop`.

**Comment by michaelficarra** [comment]
I have a strong preference for `drop` over `skip`. There's no cursor; the values are lost (dropped).

**Comment by tabatkins** [comment]
I was just about to post this same issue; when I've written a `take()` helper for myself, I've always also needed `drop()`.

(And I do prefer `drop` over `skip`, tho my preference isn't strong.)
