### ISSUE TITLE
Consider some of the methods in iterable-query as well

### ISSUE THREAD

**Issue by rbuckton** [tc39-transfer/proposal-iterator-helpers#15]
https://www.npmjs.com/package/iterable-query has a number of additional useful methods for iterables.

**Comment by michaelficarra** [comment]
Do you have a specific suggestion of what method(s) should be included? If you're asking for this library to be added to the comparison table, I don't think that would be appropriate for a library that sees such low adoption currently.

**Comment by rbuckton** [comment]
I'm writing up some of the methods I would find highly useful and will post a follow-up shortly.

**Comment by rbuckton** [comment]
https://rbuckton.github.io/iterable-query/modules/_iterable_query_fn_.html is a list of pretty much all of the functions supported by the library. Some of the ones I think would be useful to see are:

- `span`
- `break`
- `first` (seems to be missing from the list, since it has `last`)
- `single`
- `orderBy`/`orderByDescending`/`thenBy`/`thenByDescending`
- `toMap`
- `toSet`
- `toObject`
- `unzip`
- `includes`
- `includesSequence`
- `startsWith`
- `endsWith`
- `concat`
- `groupBy`
- `groupJoin`
- `join`
- `scan`
- `scanRight`
- `spanMap`
- `skipUntil`
- `skipRight`
- `takeUntil`
- `takeRight`
- Any of the `*By` methods (which take a key selector to use for filtering/comparing/etc).

**Comment by michaelficarra** [comment]
I would really prefer we not try to import an iteration library wholesale. There are two outcomes with that:

1. We do not give each new function the appropriate level of scrutiny, and we later regret some of the minor idiosyncrasies.
1. We give each new function the appropriate level of scrutiny, and this proposal languishes in committee forever, with developers never seeing any benefit from the most obvious and agreeable functions.

Let's try really hard to limit the introduction of these to the top 5-10 most needed and least contentious functions.

**Comment by rbuckton** [comment]
I'm *not* recommending we import an iteration library wholesale (there's quite a bit more in my project that serve specific corner cases that aren't needed here). Specifically, the issue topic is to consider *some* of the methods. Many of these exist in `itertools`, `lodash`, and `System.Linq.Enumerable` as well.

However, If we keep to such a small set of core functions (i.e. 5-10 as you say), users will *still* need to use other libraries for other very common operations. This also opens the possibility of 3rd parties adding a shim for their favorite iteration method that would eventually become a web compatibility nightmare (i.e. we would be forced to freeze `%IteratorPrototype%` to prevent this).

Many languages that have this or a similar capability _do_ have a fairly comprehensive set of iteration methods to rely on. I often *heavily* rely on these kinds of capabilities, and without a fairly comprehensive set of operations to rely on, I don't find this feature compelling.

**Comment by bakkot** [comment]
For what it's worth, I'd find this feature compelling even if it only had `map`, `filter`, and `reduce`.

**Comment by rbuckton** [comment]
Since this is more about what methods should be included, I'm going to close this in favor of furthering the discussion in #4 about what methods we should possibly cover.

**Comment by michaelficarra** [comment]
@rbuckton I don't think that is the purpose of #4. I opened #13 for that purpose.
