### ISSUE TITLE
Should map()/filter()/reduce() have a thisArg?

### ISSUE THREAD

**Issue by domenic** [tc39-transfer/proposal-iterator-helpers#6]
Personally I would really like it if the answer was "no". That's a remnant of the pre-`.bind()` era, as far as I'm concerned.

But, consistency would demand "yes". A classic consistency vs. goodness tradeoff.

Something to discuss!

**Comment by devsnek** [comment]
I've thought about this for a bit and honestly I can't decide one way or the other.

**Comment by ljharb** [comment]
Given `.bind` and arrow functions, if it's the only inconsistency it seems reasonable to move away from it; `reduce` and `reduceRight` have no `thisArg` as well.

**Comment by devsnek** [comment]
This seems settled, i'll close it out
